#!/bin/tcsh
if ( $#argv == 1 ) then 
    if ( -f $1 && -r $1 ) then 
        echo " $1 Es un archivo y puedes leerlo"
    else if ( -f $1 ) then
        echo "$1 Es un archivo, pero no puedes leerlo" 
    else 
        echo "$1 No es un archivo ordinario" 
else
    echo "Uso:  $0 archivo"  
endif
