#!/bin/tcsh
echo $0          # El nombre del comando
echo $#argv      # Numero de argumentos
echo $*          # Todos los argumentos
echo $1          # El primer argumento
echo $4          # El cuarto argumento
echo "pid=$$"    # El pid
